/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2025-09-24 00:37:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/G:/01_Master/04_Update/大四下学期/campusHelp/apache-tomcat-9.0.80/webapps/campusHelp/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1554295518000L));
    _jspx_dependants.put("jar:file:/G:/01_Master/04_Update/大四下学期/campusHelp/apache-tomcat-9.0.80/webapps/campusHelp/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<title>登录</title>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("<!--\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("	-->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/layui/css/layui.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"layui-layout layui-layout-admin\">\r\n");
      out.write("		<div class=\"layui-header\">\r\n");
      out.write("			<div class=\"layui-logo\">校园即时服务平台</div>\r\n");
      out.write("			<!-- 头部区域（可配合layui已有的水平导航） -->\r\n");
      out.write("			<ul class=\"layui-nav layui-layout-left\">\r\n");
      out.write("				<li class=\"layui-nav-item\"><a href=\"\">任务中心</a></li>\r\n");
      out.write("                <li class=\"layui-nav-item\"><a href=\"task/productlist.do\">商品中心</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<ul class=\"layui-nav layui-layout-right\">\r\n");
      out.write("				<li class=\"layui-nav-item\"><a href=\"register.jsp\">注册</a></li>\r\n");
      out.write("				<li class=\"layui-nav-item\"><a href=\"login.jsp\">登录</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"layui-side layui-bg-black\">\r\n");
      out.write("			<div class=\"layui-side-scroll\">\r\n");
      out.write("				<!-- 左侧导航区域（可配合layui已有的垂直导航） -->\r\n");
      out.write("				<ul class=\"layui-nav layui-nav-tree\" lay-filter=\"test\">\r\n");
      out.write("					<li class=\"layui-nav-item layui-this\"><a href=\"\">校园即时服务平台</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 内容主体区域-->\r\n");
      out.write("		<div class=\"layui-body \">\r\n");
      out.write("\r\n");
      out.write("			<div style=\"padding: 30px;\" class=\"layui-fluid\">\r\n");
      out.write("				<div class=\"layui-row\">\r\n");
      out.write("					<div class=\"layui-col-md12\">\r\n");
      out.write("						<span class=\"layui-badge-dot\"></span> <span\r\n");
      out.write("							class=\"layui-badge-dot layui-bg-orange\"></span> <span\r\n");
      out.write("							class=\"layui-badge-dot layui-bg-green\"></span> <span\r\n");
      out.write("							class=\"layui-badge-dot layui-bg-cyan\"></span> <span\r\n");
      out.write("							class=\"layui-badge-dot layui-bg-blue\"></span> <span\r\n");
      out.write("							class=\"layui-badge-dot layui-bg-black\"></span> <span\r\n");
      out.write("							class=\"layui-badge-dot layui-bg-gray\"></span>\r\n");
      out.write("						<fieldset class=\"layui-elem-field layui-field-title\"\r\n");
      out.write("							style=\"margin-top: 30px;\">\r\n");
      out.write("							<legend>登录</legend>\r\n");
      out.write("						</fieldset>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"layui-row\">\r\n");
      out.write("					<div class=\"layui-col-md3\">&nbsp;</div>\r\n");
      out.write("					<div class=\"layui-col-md6\">\r\n");
      out.write("						<fieldset class=\"layui-elem-field\">\r\n");
      out.write("							<legend>输入信息</legend>\r\n");
      out.write("							<div class=\"layui-field-box\">\r\n");
      out.write("								<div class=\"layui-tab\">\r\n");
      out.write("									<ul class=\"layui-tab-title\">\r\n");
      out.write("										<li class=\"layui-this\">普通用户登录</li>\r\n");
      out.write("										<li>管理员登录</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("									<div class=\"layui-tab-content\">\r\n");
      out.write("										<div class=\"layui-tab-item layui-show\">\r\n");
      out.write("											<form id=\"loginform\" class=\"layui-form layui-form-pane\"\r\n");
      out.write("												action=\"user/login.do\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("												<div class=\"layui-form-item\">\r\n");
      out.write("													<label class=\"layui-form-label\">学号</label>\r\n");
      out.write("													<div class=\"layui-input-inline\">\r\n");
      out.write("														<input type=\"text\" name=\"studentid\" lay-verify=\"studentid\"\r\n");
      out.write("															placeholder=\"请输入\" autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"layui-form-item\">\r\n");
      out.write("													<label class=\"layui-form-label\">密码</label>\r\n");
      out.write("													<div class=\"layui-input-inline\">\r\n");
      out.write("														<input type=\"password\" name=\"password\" placeholder=\"请输入密码\"\r\n");
      out.write("															lay-verify=\"password\" autocomplete=\"off\"\r\n");
      out.write("															class=\"layui-input\">\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"layui-form-mid layui-word-aux\">请务必记住密码</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"layui-form-item\">\r\n");
      out.write("													<button class=\"layui-btn\" lay-submit=\"loginform\"\r\n");
      out.write("														lay-filter=\"loginform\">登录</button>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("											</form>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"layui-tab-item\">\r\n");
      out.write("											<form id=\"adminform\" class=\"layui-form layui-form-pane\"\r\n");
      out.write("												action=\"admin/adminlogin.do\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("												<div class=\"layui-form-item\">\r\n");
      out.write("													<label class=\"layui-form-label\">管理员账号</label>\r\n");
      out.write("													<div class=\"layui-input-inline\">\r\n");
      out.write("														<input type=\"text\" name=\"account\" lay-verify=\"account\"\r\n");
      out.write("															placeholder=\"请输入\" autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"layui-form-item\">\r\n");
      out.write("													<label class=\"layui-form-label\">密码</label>\r\n");
      out.write("													<div class=\"layui-input-inline\">\r\n");
      out.write("														<input type=\"password\" name=\"password\" placeholder=\"请输入密码\"\r\n");
      out.write("															lay-verify=\"password\" autocomplete=\"off\"\r\n");
      out.write("															class=\"layui-input\">\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"layui-form-item\">\r\n");
      out.write("													<button class=\"layui-btn\" lay-submit=\"adminform\"\r\n");
      out.write("														lay-filter=\"adminform\">登录</button>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("											</form>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</fieldset>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"layui-footer\">\r\n");
      out.write("			<!-- 底部固定区域 -->\r\n");
      out.write("			©  - 校园即时服务平台办公电话：6666666\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/layui/layui.all.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	layui.use([ 'form', 'laydate' ], function() {\r\n");
      out.write("		var form = layui.form,\r\n");
      out.write("			layer = layui.layer,\r\n");
      out.write("			laydate = layui.laydate;\r\n");
      out.write("\r\n");
      out.write("		//日期\r\n");
      out.write("		laydate.render({\r\n");
      out.write("			elem : '#date'\r\n");
      out.write("		});\r\n");
      out.write("		laydate.render({\r\n");
      out.write("			elem : '#date1'\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		//自定义验证规则\r\n");
      out.write("		form.verify({\r\n");
      out.write("			studentid : function(value) {\r\n");
      out.write("				if (value.length < 5) {\r\n");
      out.write("					return '学号至少是得5个字符的啊';\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			account : function(value) {\r\n");
      out.write("				if (value.length < 5) {\r\n");
      out.write("					return '账号至少是得5个字符的啊';\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			password : [ /(.+){6,12}$/, '密码是6到12位的哦' ]\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		//监听提交\r\n");
      out.write("		form.on('submit(loginform)', function(data) {\r\n");
      out.write("			/*layer.alert(JSON.stringify(data.field), {\r\n");
      out.write("				title : '最终的提交信息'\r\n");
      out.write("			})*/\r\n");
      out.write("		//return false;\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		//监听提交\r\n");
      out.write("		form.on('submit(adminform)', function(data) {\r\n");
      out.write("			/*layer.alert(JSON.stringify(data.field), {\r\n");
      out.write("				title : '最终的提交信息'\r\n");
      out.write("			})*/\r\n");
      out.write("			//return false;\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /login.jsp(150,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty msg }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<script type=\"text/javascript\">\r\n");
          out.write("				alert(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\");\r\n");
          out.write("			</script>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
